### ISSUE TITLE
Remove /en/latest from URLs

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ecosystem-documentation#22]
As I really doubt we will need to version the main website or to translate and keep it in sync, we should switch to single version layout, which is removing the `/en/latest` prefix.

As part of the move, I do know how to configure automatic redirects, as ansible-lint project used this feature for few years.

**Comment by acozine** [comment]
What are the advantages of removing `/en/latest`? Is this more than "we don't need it"? Does it solve a problem we have?

**Comment by samccann** [comment]
Discussed in the DaWGS meeting a bit.
1 - What problem does this solve, or what benefit does it bring us to remove these?
2 - Keeping them gives us more flexibility in the future to version if we need to, or support translation at some point.

**Comment by oraNod** [comment]
@samccann The only project I can think of that has translated docs is core. We haven't added the Japanese versions to the Read The Docs stage project but... if we do want to fully migrate core docs to RTD then I believe we'll want to hang on to the `/<lang>/` part of the urls.

Has there been a change and there is no longer a team providing core translations?

**Comment by samccann** [comment]
I don't know the status of translations.

But maybe a better discussion is - what is the impact if we remove both /en/ and /latest/ in the url? 

So for /en/ if we have a translation in the future, we can just publish to /jp/xxx right? No impact on the english version?

For /latest/ - what do we do if some ecosystem cross-project guide must be versioned?  Perhaps it's not a 'solvable' problem because the version that say cross-project foo guide needs won't match a version that  cross-project-bar guide needs. 

So for that, we'd likely only want one version for released projects. But is there any need for a 'devel' version? Because removing this from the url also removes the ability to have a way to view docs before a release so to speak, like we do with package/core docs.  Where I could see this happening is that someone wants to add super-new-feature to say the devTools guides for an upcoming release.  That PR can't merge because we only have one version  - the released version.  To me it suggests a bigger chance of muddying the current/released version with future docs that someone writes before a release.

**Comment by oraNod** [comment]
FYI this is a change in Read The Docs that would apply to the ansible namespace.

![image](https://github.com/ansible/ecosystem-documentation/assets/32749632/a7a59a7b-796d-44cd-959b-75ecea0764b7)

https://docs.readthedocs.io/en/stable/versioning-schemes.html#single-version-without-translations

**Comment by samccann** [comment]
So we don't want this across the whole ansible namespace for sure!  But interesting the main 'tech' example given is for SaaS, which is only really applicable to galaxy.

**Comment by oraNod** [comment]
Closing this as done. We're going to archive this repo and I've moved the docsite landing pages to the Ansible project in RTD. When I did that, I selected the single version without translations versioning scheme.
